spring:
  application:
    name: UrlShortener

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sortUrl}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  app:
    secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentOnly}
    expiration: ${JWT_EXPIRATION:300000}
    refreshtoken: ${JWT_REFRESH_EXPIRATION:172800000}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
