spring:
  application:
    name: UrlShortener

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  app:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refreshtoken: ${JWT_REFRESH_EXPIRATION}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}

server:
  port: ${SERVER_PORT:8080}
